"use client";

import { useEffect, useState } from "react";
import { Info } from "lucide-react";
import type { MatrixParams } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { BomTab } from "@/components/workbench/BomTab";

/**
 * Step 2 of the guided flow: confirm the items being compared and assign an
 * HS code to each so the matrix can apply real statutory duty. Lines without
 * an HS code fall back to the flat duty %, freight and LC set here.
 */
export function DutyStep({
  projectId,
  params,
  onChange,
}: {
  projectId: string;
  params: MatrixParams;
  onChange: (p: MatrixParams) => void;
}) {
  return (
    <div className="space-y-4">
      <div className="flex items-start gap-3 rounded-xl border border-teal/30 bg-teal/5 px-4 py-3 text-sm">
        <Info className="mt-0.5 h-4 w-4 shrink-0 text-teal" />
        <p className="text-muted-foreground">
          Items and suppliers are pulled from your uploaded quotes automatically.
          Each item&apos;s{" "}
          <strong className="text-foreground">HS code</strong> is generated by AI
          when this step opens — review the suggestion and select it (or edit it)
          so the matrix applies Pakistan&apos;s real duty stack. Anything left
          without an HS code uses the flat duty %, freight and LC at the bottom.
        </p>
      </div>

      <BomTab projectId={projectId} />

      <FlatDutyAssumptions params={params} onChange={onChange} />
    </div>
  );
}

function FlatDutyAssumptions({
  params,
  onChange,
}: {
  params: MatrixParams;
  onChange: (p: MatrixParams) => void;
}) {
  const [duty, setDuty] = useState(pctString(params.duty_pct));
  const [lc, setLc] = useState(pctString(params.lc_pct));
  const [freight, setFreight] = useState(numString(params.freight_per_unit));

  useEffect(() => {
    setDuty(pctString(params.duty_pct));
    setLc(pctString(params.lc_pct));
    setFreight(numString(params.freight_per_unit));
  }, [params.duty_pct, params.lc_pct, params.freight_per_unit]);

  function commit(next: Partial<MatrixParams>) {
    onChange({ ...params, ...next });
  }

  return (
    <div className="space-y-2 rounded-xl border border-border/60 bg-card/70 p-3 shadow-soft">
      <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
        Fallback assumptions (for items without an HS code)
      </p>
      <div className="grid grid-cols-3 items-end gap-3 sm:flex sm:flex-wrap sm:gap-4">
        <Field label="Duty %">
          <Input
            className="w-full sm:w-24"
            type="number"
            inputMode="decimal"
            value={duty}
            aria-label="Duty percent"
            onChange={(e) => setDuty(e.target.value)}
            onBlur={() => commit({ duty_pct: fracFromPct(duty) })}
          />
        </Field>
        <Field label="Freight / unit">
          <Input
            className="w-full sm:w-28"
            type="number"
            inputMode="decimal"
            value={freight}
            aria-label="Freight per unit"
            onChange={(e) => setFreight(e.target.value)}
            onBlur={() => commit({ freight_per_unit: numFromStr(freight) })}
          />
        </Field>
        <Field label="LC %">
          <Input
            className="w-full sm:w-24"
            type="number"
            inputMode="decimal"
            value={lc}
            aria-label="LC percent"
            onChange={(e) => setLc(e.target.value)}
            onBlur={() => commit({ lc_pct: fracFromPct(lc) })}
          />
        </Field>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-1">
      <Label className="text-xs text-muted-foreground">{label}</Label>
      {children}
    </div>
  );
}

function pctString(frac: number | undefined): string {
  if (frac === undefined || frac === null) return "";
  return String(Math.round(frac * 1000) / 10);
}
function numString(n: number | undefined): string {
  if (n === undefined || n === null) return "";
  return String(n);
}
function fracFromPct(s: string): number | undefined {
  const n = Number(s);
  return s.trim() === "" || Number.isNaN(n) ? undefined : n / 100;
}
function numFromStr(s: string): number | undefined {
  const n = Number(s);
  return s.trim() === "" || Number.isNaN(n) ? undefined : n;
}
